apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: tripinsights-vault-123 
spec:
  provider: azure
  secretObjects:                           
    - secretName: db-creds
      type: Opaque
      data:
        - objectName: sql-user
          key: sql-user
        - objectName: sql-password
          key: sql-password 
  parameters:
    usePodIdentity: "false"
    keyvaultName: "tripinsights-vault-123" 
    objects: |
      array:
        - |
          objectName: sql-user
          objectAlias: sql-user
          objectType: secret 
        - | 
          objectName: sql-password
          objectAlias: sql-password
          objectType: secret                 
    tenantId: "3f69e2d4-5d20-4160-afe1-fd6bbeaa18cf"                          
